<a href="https://colab.research.google.com/github/iamnaofil/iamnaofil/blob/main/Practicing_Numpy_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
#Print NUMPY VERSION
np.__version__


'1.22.4'

In [ ]:
#Show Configuration of Numpy
np.show_config()

In [8]:
#Create a null vector of size 10
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
#How to find the memory size of any array

memory_size=null_vector.nbytes
print(memory_size)
#here a single item 0. is 8 Byte so 8 x 10 is 80

80


In [14]:
# Create a null vector of size 10 but the fifth value which is 1
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
# Create a vector with values ranging from 10 to 49
vec1=np.arange(10,50)
print(vec1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
#Reverse the Vector
vec1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

**Create a 3x3 matrix with values ranging from 0 to 8**

In [31]:
# np.arange to generating arrays of sequential numbers. With just three arguments,
# arange(start) OR arange(start,stop,stop)
#reshape (set shape of the array into anothe shape like 2x2, 3x3,1x9 etc)
matrix=np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
#When you need an array of evenly spaced numbers, np.linspace
#linspace(start,stopwhich is included,  step)
matrix2=np.linspace(0,8,9).reshape(3,3)
print(matrix2.astype('int16'))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
#random havie more function, the randint is for integer random
matrix3=np.random.randint(0,8,(3,3))
print(np.sort(matrix3))

[[1 3 5]
 [0 0 5]
 [1 1 6]]


**Find Indices of  numbers**

In [56]:
arr1=np.array([10,30,70,70,0,110,0,9,None])
arr1

array([10, 30, 70, 70, 0, 110, 0, 9, None], dtype=object)

In [57]:
#what is index of 70
#.where is used for conditional indexing,replacing value,data analysis
np.where(arr1==70)

(array([2, 3]),)

In [59]:
np.where(arr1==None)

(array([8]),)

In [60]:
np.where(arr1==0)

(array([4, 6]),)

**Create 3 x 3 Identity Matrix**

In [64]:
identity=np.eye(3,3).astype(int)
print(identity)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [66]:
identity2=np.eye(3,3,dtype='int')
print(identity2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [73]:
#Check the element s size , occupation of memory
import sys
print(sys.getsizeof(identity)*identity.itemsize)
print(sys.getsizeof(identity2)*identity2.itemsize)

1600
1600


**Create 10x10 Matrix (randomly) find MIN MAX**

In [75]:
ran=np.random.randint(1,100,100, dtype='int').reshape(10,10)
print(ran)

[[28 55 89 99 79 80 54 78 39 75]
 [19 77 28 91 65 37 42 25 53 77]
 [82 33 85  7 90 70 25  3 60 37]
 [10 31 19  8 47 87 57  3 36 64]
 [ 2 95 56 52 56 71 90 27 31 68]
 [34 70 58 47 40 10 10 79 71 73]
 [15 82 42 94 18 27  6 48 45 58]
 [42 30 90 31 11 34 99 28 57 11]
 [91 24 77 73 25 83 58 89 15 53]
 [40  5 77 14 86 15 59 27 66 33]]


In [85]:
#find Minimum value
ran.min()

2

In [83]:
#Where is that minimum value in array (index of 2 )
np.where(ran==2)

(array([4]), array([0]))

In [86]:
ran.max()

99

In [94]:
np.where(ran==99)

(array([0, 7]), array([3, 6]))

**Create a random vector of size 30 and find the mean value**

In [106]:
random=np.random.randint(0,29,30).astype('int')
print(random)

[19 18 19 20 12  9  3  4 11  4 17  0  8 23  8  2  6 15 22  1  8  7  8  8
 16 17  9 18  1  7]


In [108]:
print(random.mean())

10.666666666666666


In [109]:
print(int(random.mean()))

10


**Create a 2d array with 1 on the border and 0 inside**

In [115]:
ones=np.ones(25).reshape(5,5).astype('int')

In [117]:
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [119]:
#Use Slcing / Indeing
ones[1:4,1:4]=0

In [121]:
print(ones)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**How to add a border (filled with 0's) around an existing array? **

In [143]:
ones=np.ones(25).reshape(5,5).astype('int')
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [144]:
ones[0:1,:]=ones[:,0:1]=0

In [145]:
print(ones)

[[0 0 0 0 0]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]]


In [146]:
ones[:,4:]=ones[4:,:]=0

In [147]:
print(ones)


[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [163]:
ones[0,:]=99

In [164]:
ones[:,-1]=99

In [165]:
ones[4:,:]=99

In [166]:
ones[:,4:]=99

In [167]:
print(ones)

[[99 99 99 99 99]
 [ 0  1  1  1 99]
 [ 0  1  1  1 99]
 [ 0  1  1  1 99]
 [99 99 99 99 99]]


In [168]:
0*np.nan

nan

In [172]:
np.inf!=np.nan

True

In [173]:
np.nan-np.nan

nan

In [174]:
np.nan in set([np.nan])

True

In [175]:
0.3==3*0.1

False

In [177]:
np.nan==np.nan

False